import { readFileSync, writeFileSync } from "fs";

// Tiny hand-written widget (no SDK bundle) — read the literal HTML and emit it as a JS string.
const html = readFileSync(new URL("./widget.html", import.meta.url), "utf-8");
const out = `// AUTO-GENERATED by geoflix-widget/build.js — do not edit.\nexport const WIDGET_HTML = ${JSON.stringify(html)};\n`;
writeFileSync(new URL("../app/api/[transport]/widget-html.js", import.meta.url), out);
console.log("Wrote widget HTML (" + html.length + " bytes) to app/api/[transport]/widget-html.js");
