import { build } from "esbuild";
import { writeFileSync } from "fs";

const result = await build({
  entryPoints: ["src/widget.js"],
  bundle: true,
  minify: true,
  format: "iife",
  write: false,
  target: ["es2020"],
});

const js = result.outputFiles[0].text;

const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  html,body{margin:0;padding:0;background:#0a0a0a}
  #root{display:flex;align-items:center;justify-content:center;min-height:120px}
  #root video,#root img{width:100%;height:auto;display:block;border-radius:12px}
  .msg{color:#888;font:14px -apple-system,system-ui,sans-serif;padding:24px}
</style></head>
<body><div id="root"><div class="msg">Loading…</div></div>
<script>${js}</script>
</body></html>`;

// Emit as a JS module the Next.js route can import (serverless-friendly, no fs reads).
const out = `// AUTO-GENERATED by geoflix-widget/build.js — do not edit.\nexport const WIDGET_HTML = ${JSON.stringify(html)};\n`;
writeFileSync(new URL("../app/api/[transport]/widget-html.js", import.meta.url), out);
console.log("Wrote widget HTML (" + html.length + " bytes) to app/api/[transport]/widget-html.js");
